stages:
  - build

sprint0:
  stage: build
  only:
    - master
  script: cd presentations/sprint0/; make
  artifacts:
    name: sprint0
    paths:
    - presentations/sprint0/presentation.pdf

sprint1:
  stage: build
  only:
    - master
  script: cd presentations/sprint1/; make
  artifacts:
    name: sprint1
    paths:
    - presentations/sprint1/presentation.pdf

oFonoSlides:
  stage: build
  only:
    - master
  script: cd presentations/OS\&Co/oFono; make
  artifacts:
    name: oFonoSlides
    paths:
    - presentations/OS&Co/oFono/presentation.pdf

gpsSlides:
  stage: build
  only:
    - master
  script: cd presentations/OS\&Co/gps; make
  artifacts:
    name: gpsSlides
    paths:
    - presentations/OS&Co/gps/presentation.pdf