stages:
  - build

presentation00:
  stage: build
  script: cd presentations/sprint0/; make
  artifacts:
    name: presentation00
    paths:
    - presentations/sprint0/presentation.pdf

oFonoSlides:
  stage: build
  script: cd presentations/OS\&Co/oFono; make
  artifacts:
    name: oFonoSlides
    paths:
    - presentations/OS&Co/oFono/presentation.pdf

gpsSlides:
  stage: build
  script: cd presentations/OS\&Co/gps; make
  artifacts:
    name: gpsSlides
    paths:
    - presentations/OS&Co/gps/presentation.pdf