/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p OfonoVoiceCallManagerNew -a adCl newOfono.xml org.ofono.VoiceCallManager
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "OfonoVoiceCallManagerAdaptor.h"
#include "Struct.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include "VoiceCallManager.h"

/*
 * Implementation of adaptorO class VoiceCallManagerAdaptor
 */

VoiceCallManagerAdaptor::VoiceCallManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);

}

VoiceCallManagerAdaptor::~VoiceCallManagerAdaptor()
{
    // destructor
}

void VoiceCallManagerAdaptor::CallAddedSlot(const QDBusObjectPath& path, const QVariantMap& properties)
{

}

QDBusObjectPath VoiceCallManagerAdaptor::Dial(const QString &number, const QString &hide_callerid)
{
    // handle method call org.ofono.VoiceCallManager.Dial
    QDBusObjectPath path;
    QMetaObject::invokeMethod(parent(), "Dial", Q_RETURN_ARG(QDBusObjectPath, path), Q_ARG(QString, number), Q_ARG(QString, hide_callerid));
    return path;
}

void VoiceCallManagerAdaptor::GetCalls()
{
    // handle method call org.ofono.VoiceCallManager.GetCalls
    QMetaObject::invokeMethod(parent(), "GetCalls");
    writeLog("VoiceCallManagerAdaptor | GetCalls", INFO);
}

QVariantMap VoiceCallManagerAdaptor::GetProperties()
{
    // handle method call org.ofono.VoiceCallManager.GetProperties
    QVariantMap properties;
    QMetaObject::invokeMethod(parent(), "GetProperties", Q_RETURN_ARG(QVariantMap, properties));
    return properties;
}



