######################################################################
# Automatically generated by qmake (3.0) ?? ???. 26 11:57:00 2017
######################################################################

QT += core dbus
TEMPLATE = app
TARGET = test-speaker-volumeGCC
INCLUDEPATH +=.
QMAKE_CXXFLAGS += -std=c++0x

# Input
SOURCES += set-speaker-volume.cpp
