######################################################################
# Automatically generated by qmake (3.0) ?? ???. 26 11:57:00 2017
######################################################################

QT += core dbus
TEMPLATE = app
TARGET = buttonsDaemon
INCLUDEPATH +=.
QMAKE_CXXFLAGS += -std=c++0x -pthread 
LIBS += -pthread

# Input
SOURCES += main.cpp GPIOController.cpp
