/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p OfonoVoiceCallManagerNew -a adCl newOfono.xml org.ofono.VoiceCallManager
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ADCL_H
#define ADCL_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ofono.VoiceCallManager
 */
class VoiceCallManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ofono.VoiceCallManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ofono.VoiceCallManager\">\n"
"    <method name=\"GetProperties\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"Dial\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"number\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"hide_callerid\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"GetCalls\"/>\n"
"    <signal name=\"CallAdded\">\n"
"      <annotation name=\"org.qtproject.QtDBus.QtTypeName.Out0\" value=\"QVariantMap\"/>\n"
"      <arg name=\"path\" type=\"o\"/>\n"
"      <arg name=\"properties\" type=\"a{sv}\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    VoiceCallManagerAdaptor(QObject *parent);
    virtual ~VoiceCallManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath Dial(const QString &number, const QString &hide_callerid);
    void GetCalls();
    void CallAddedSlot(const QDBusObjectPath& path, const QVariantMap& properties);
    QVariantMap GetProperties();
Q_SIGNALS: // SIGNALS
    void CallAdded(const QDBusObjectPath& path, const QVariantMap& properties);
};

#endif
